feat: Select Smaller/Larger Syntax Nodes
KDAB/knut pull request #105
Opened 2024-07-10 15:45 UTC by LeonMatthesKDAB

This allows navigating the code semantically.

Fix #64

2024-07-11 18:21 UTC, narnaud requested changes
Very nice, it's actually working nicely.
The previous/next sibling can be really useful for fast scripting.

Small comments, nothing serious.

2024-07-11 18:21 UTC, narnaud commented on src/core/codedocument.cpp
> +    return position();
Same here `LOG_RETURN("pos", position());`

2024-07-11 18:21 UTC, narnaud commented on src/core/codedocument.cpp
> +
We should probably show a info and stop here if there a no selection.
When testing, I was puzzled by the warning I got:
```
[2024-07-11 20:05:01.730] [warning] TextDocument::createRangeMark: Creating a range mark with an empty range.
```

2024-07-11 18:21 UTC, narnaud commented on src/core/codedocument.cpp
> +    return position();
Same here `LOG_RETURN("pos", position());`

2024-07-11 18:21 UTC, narnaud commented on src/gui/mainwindow.h
> -    void selectBlockUp();
Please keep it, even if it's doable with selectLargerNode, it's slightly different enough to make sense to keep it around.

Shortcut is Ctrl+Shift+U, should be ok

2024-07-11 18:21 UTC, narnaud commented on src/gui/mainwindow.cpp
> +    ui->actionSelectSmallerSyntaxNode->setEnabled(isCodeDocument);
Would be nice to disable if there are no selections, as it does nothing.

2024-07-11 18:21 UTC, narnaud commented on src/gui/mainwindow.cpp
> +#define FORWARD_TO_DOCUMENT(TYPE, FUNCTION)                                                                            \
Nice, can you move before the constructor, and add a bit of documentation on the macros?

The reason is in case someone add a method before in the header file, and create the definition from the IDE, it will most likely be created before the macro.

I think you can also use it for selectAll below.

2024-07-15 12:31 UTC, LeonMatthesKDAB commented on src/gui/mainwindow.cpp
> +#define FORWARD_TO_DOCUMENT(TYPE, FUNCTION)                                                                            \
Done

2024-07-15 12:32 UTC, LeonMatthesKDAB commented on src/gui/mainwindow.h
> -    void selectBlockUp();
Re-added it

2024-07-15 12:38 UTC, LeonMatthesKDAB commented on src/core/codedocument.cpp
> +
Done

2024-07-15 12:38 UTC, LeonMatthesKDAB commented on src/core/codedocument.cpp
> +    return position();
Done for all 4 methods

2024-07-15 13:28 UTC, narnaud approved these changes

2024-07-15 13:31 UTC, narnaud commented on src/gui/mainwindow.cpp
> +    ui->actionSelectSmallerSyntaxNode->setEnabled(isCodeDocument);
We have the warning, probably enough.
We can add a task for later, but it's probably good enough.

2024-07-15 14:41 UTC, merged