fix: save settings on exit
KDAB/knut pull request #125
Opened 2024-07-24 16:11 UTC by smnppKDAB

We add a way to save settings before exiting if there are changes. This make the tests to pass with the corrected knut.json

2024-07-24 16:28 UTC, dfaure-kdab commented
Looks good to me, but this is my idea in the first place, so I'll let @LeonMatthesKDAB review ;-)

Debugging indicated that with offscreen QPA the Settings timer had time to fire but without it, the app would exit due to lastWindowClosed(), without waiting for scriptFinished and without saving settings.

2024-07-25 06:21 UTC, LeonMatthesKDAB requested changes
Overall making sure we save the settings when the timer is still active definitely makes sense.
However, can you try calling saveOnExit() in the Settings destructor, instead of connecting it to scriptFinished?

It just seems like that would be the more fool-proof option and should cover more cases.

2024-07-25 07:00 UTC, LeonMatthesKDAB commented
Hm, I just tried testing knut locally and this PR actually doesn't seem to fix the issue :thinking: 
Strangely 2/3 tests fail without actually telling me which file is different.
And the other one tells me that knut.json is missing in the `expected` folder.
Which to me almost sounds like it's now saving settings that it didn't used to before.

2024-07-25 07:16 UTC, LeonMatthesKDAB commented
So for the mfc_convert_ribbon test I get the following files:

expected
```
{
    "qtui": {
        "custom_widgets": [
            "MySliderCtrl|\"mysliderctrl.h\"|QSlider"
        ]
    }
}
```

actual
```
{
    "qtui": {
        "custom_widgets": [
            "MySliderCtrl|\"mysliderctrl.h\"|QSlider"
        ]
    },
    "rc": {
        "dialog_flags": [
            "UpdateGeometry",
            "UseIdForPixmap"
        ],
        "dialog_scalex": 1.5,
        "dialog_scaley": 1.65
    }
}
```

So is this change correct?

2024-07-25 08:04 UTC, dfaure-kdab commented
Don't forget the additional variable of running tests via ctest/CI versus running tests directly (QtCreator or command-line).
This patch here is about ensuring that both leads to the same result. Previously, ctest/CI would save on exit while QtCreator/cmdline would not (because of lastWindowClosed).

So yes, if you stay within the ctest/CI use case, this patch isn't needed. But better save in all cases to minimize surprises.

Calling saveOnExit() in the Settings destructor is an interesting idea, I'll let @smnppKDAB test it.

2024-07-25 08:28 UTC, smnppKDAB commented
> Hm, so for me the tests only pass with these patches: https://codereview.kdab.com/c/kdab/mfc-utils/+/144535
> 
> Are these updates expected? I'm not too familiar with mfc-utils, so can't tell if they are sensible.

Here is the corresponding MR : https://codereview.kdab.com/c/kdab/mfc-utils/+/144526

2024-07-25 08:38 UTC, dfaure-kdab commented on src/core/settings.h
> +    void saveOnExit();
Should be private now that it's only called internally.

2024-07-25 09:05 UTC, LeonMatthesKDAB commented
> > Hm, so for me the tests only pass with these patches: https://codereview.kdab.com/c/kdab/mfc-utils/+/144535
> > Are these updates expected? I'm not too familiar with mfc-utils, so can't tell if they are sensible.
> 
> Here is the corresponding MR : https://codereview.kdab.com/c/kdab/mfc-utils/+/144526

Oh, right, I didn't know about that MR. Please link any MRs that a PR is related to next time :)

2024-07-25 09:08 UTC, LeonMatthesKDAB commented on src/core/settings.h
> +    void saveOnExit();
Why has this been resolved? It is still public.

2024-07-25 09:25 UTC, LeonMatthesKDAB approved these changes

2024-07-25 11:58 UTC, dfaure-kdab approved these changes

2024-07-25 11:58 UTC, merged