fix: do not run tests if the path to the directory doesn't exist
KDAB/knut pull request #126
Opened 2024-07-25 10:12 UTC by smnppKDAB

2024-07-25 12:37 UTC, LeonMatthesKDAB requested changes

2024-07-25 12:37 UTC, LeonMatthesKDAB commented on src/core/knutcore.cpp
> +            return;
Hm, when testing this, Knut actually doesn't exit, it just hangs forever until I kill it, and the GUI also doesn't open.

So unless we open a GUI afterwards, we probably want to exit(1) instead?

2024-07-25 12:38 UTC, dfaure-kdab commented on src/core/knutcore.cpp
> +            return;
Heh I hadn't seen this comment yet ;)

2024-07-25 12:46 UTC, LeonMatthesKDAB commented on src/core/knutcore.cpp
> +            return;
I think not even `qApp->exit()` will actually help here, as the event loop is not yet running?
At least that is suggested by: https://doc.qt.io/qt-6/qcoreapplication.html#exit

2024-07-25 12:46 UTC, LeonMatthesKDAB commented on src/core/knutcore.cpp
> +            return;
But maybe it then picks it up in the `exec` call?
Unsure about that.

2024-07-26 06:19 UTC, LeonMatthesKDAB requested changes
For me, Knut still isn't exiting when the project path doesn't exist.

2024-07-26 06:19 UTC, LeonMatthesKDAB commented on src/core/knutcore.cpp
> +            return;
At least for me locally this indeed does not work...

Knut is not exiting! @smnppKDAB Does it work for you?

2024-07-26 08:49 UTC, smnppKDAB commented on src/core/knutcore.cpp
> +            return;
now it's working for me

2024-07-26 09:21 UTC, dfaure-kdab approved these changes

2024-07-29 07:06 UTC, LeonMatthesKDAB approved these changes

2024-07-29 07:06 UTC, merged