feat: add a find in files API to `Project`
KDAB/knut pull request #143
Opened 2024-08-07 13:50 UTC by smnppKDAB

The methode return a list of document + position of the find items.
The method uses ripgrep (rg) for searching, which must be installed and accessible in the system's PATH.
The `pattern` parameter should be a valid regular expression.
Fixes KDAB#21

2024-08-07 14:25 UTC, dfaure-kdab requested changes

2024-08-07 14:25 UTC, dfaure-kdab commented on docs/API/knut/project.md
> +Note : The method uses ripgrep (rg) for searching, which must be installed and accessible
No space before ":" in English (unlike French)

2024-08-07 14:25 UTC, dfaure-kdab commented on docs/API/knut/project.md
> +in the system's PATH. The `pattern` parameter should be a valid regular expression.
Not necessarily "the system's".

2024-08-07 14:25 UTC, dfaure-kdab commented on src/core/project.cpp
> +QVariantList Project::findInFiles(const QString &pattern)
Could the method be marked const?

If the const is missing only because someone else forgot it on allFilesWithExtensions(), that's not a good reason ;-)

2024-08-07 14:25 UTC, dfaure-kdab commented on src/core/project.cpp
> +                      "included in your system's PATH environment variable.");
s/your system's/the/

2024-08-07 14:25 UTC, dfaure-kdab commented on src/core/project.cpp
> +    arguments << "--vimgrep"
Modern C++ allows to do this better with

    const QStringList arguments{"--vimgrep", "-u", etc.};

This way the QStringList is constructed with the right size from the start, and immediately initialized.

2024-08-07 14:25 UTC, dfaure-kdab commented on src/core/project.cpp
> +        spdlog::error("The ripgrep process failed to complete: {}", process.errorString());
Oh it completed alright, but it failed ;)
I would remove "to complete"

2024-08-07 14:25 UTC, dfaure-kdab commented on src/core/project.cpp
> +        spdlog::error("Erreur ripgrep: {}", errorOutput);
Red alert! French text! ;-)

2024-08-07 14:25 UTC, dfaure-kdab commented on src/core/project.cpp
> +    QString path = QStandardPaths::findExecutable("rg");
const QString path = ..

(same for many other variables below). Always declare const the variables that aren't modified further down. Clearer, and sometimes faster (no detaching when iterating). And sometimes it catches bugs (typos) ;)

2024-08-07 14:25 UTC, dfaure-kdab commented on src/core/project.cpp
> +            matchResult["file"] = parts[0].split("/").last();
matchResult.insert("file", ...); is better/faster.

This is explained in details in Effective STL, IIRC, I just didn't keep the reference to the item number... Maybe you can find it in the books here ;)

2024-08-07 14:25 UTC, dfaure-kdab commented on src/core/project.cpp
> +            result.append(matchResult);
You could do result.reserve(lines.count() * 3) before the loop then, to improve performance.

2024-08-07 14:25 UTC, dfaure-kdab commented on src/core/project.cpp
> +            matchResult["file"] = parts[0].split("/").last();
Returning only the filename doesn't seem like a good idea to me. What if the caller wants to actually do something with that file? They'll need at least a relative path to the project root to avoid having to search for it recursively. Worse, what if there are multiple files called main.cpp in the project?

Not sure if absolute or relative-to-project-root is better, but for sure just the filename isn't enough.

2024-08-07 14:25 UTC, dfaure-kdab commented on test_data/tst_project.qml
> +
Also check that simpleResults only contains 2 elements? It could misbehave and return false positives after the 2 that you expect.

2024-08-07 16:45 UTC, dfaure-kdab commented on docs/API/knut/project.md
> +|QVariantList |**[findInFiles](#findInFiles)**(const QString &pattern)|
I'm guessing QVariantList isn't what a QML/JS developer wants to see here, but I'm not sure what it should say instead... That's a question for the other reviewers.

2024-08-07 16:47 UTC, dfaure-kdab commented on test_data/tst_project.qml
> +        let multilineResults = Project.findInFiles(multilinePattern)
The comment about checking the length of the array applies to this one too, obviously.

2024-08-08 08:38 UTC, dfaure-kdab commented on test_data/tst_project.qml
> +        compare(simpleResults[0].file.split("knut/").pop(), "test_data/projects/mfc-tutorial/TutorialApp.cpp")
What if I clone knut in ~/knut/v1/knut/ ?  Won't this pop() return v1/?

I'm confused, actually. Do you get a full path or a relative path in `file`? This should actually be documented in the docs for your method, BTW.

2024-08-08 09:04 UTC, smnppKDAB commented on test_data/tst_project.qml
> +        compare(simpleResults[0].file.split("knut/").pop(), "test_data/projects/mfc-tutorial/TutorialApp.cpp")
@dfaure-kdab result[0].file currently gives the full path.
pop() returns the last string in the list of strings given by the split.

2024-08-08 09:57 UTC, dfaure-kdab commented on test_data/tst_project.qml
> +        compare(simpleResults[0].file.split("knut/").pop(), "test_data/projects/mfc-tutorial/TutorialApp.cpp")
OK but what if I choose to name my knut source directory "THE_BEST_TOOL_EVER" instead of "knut"? ;)

Why not just give the full path as the expected value? Something like

`compare(simpleResults[0].file, Project.root + "/TutorialApp.cpp")`

2024-08-08 12:02 UTC, dfaure-kdab commented on docs/API/knut/project.md
> +|QVariantList |**[findInFiles](#findInFiles)**(const QString &pattern)|
Thinking further about it, I guess it should be something like

    `array<map<string, any>>`

2024-08-08 17:04 UTC, dfaure-kdab commented on docs/API/knut/settings.md
> +- array<string>
regression? Any way to find out if this one still renders correctly?

2024-08-08 17:04 UTC, dfaure-kdab commented on docs/API/knut/project.md
> +|array&lt;map&lt;string, any>> |**[findInFiles](#findInFiles)**(const QString &pattern)|
Matt is right, it should be array<object>, actually.
The Javascript type Object is exactly the container for properties of any type that a QVariantMap is.

Now that I think about it, we could have done some type discovery in javascript with Message.log() to find out about this.

2024-08-08 17:04 UTC, dfaure-kdab commented on docs/API/knut/querymatch.md
> +|vector&lt;[RangeMark](../knut/rangemark.md)> |**[getAll](#getAll)**(string name)|
(pre-existing, something for future work) I'm pretty sure this "vector" should be "array" in javascript terms.

2024-08-09 12:21 UTC, dfaure-kdab submitted a review, later dismissed

2024-08-14 11:48 UTC, narnaud commented on src/core/project.cpp
> +        const auto parts = line.split(':');
This does not work on Windows, as the path starts with `C:...`
Also, for the path, it returns values like:
`C:/dev/knut/mfc-utils/examples/tutorialapp\TutorialDlg.h:17:9:/// the CTutorialApp::InitInstance function.` with a mix of / and \ - would be nice to add some consistency and use / everywhere (just a replaceAll on the string).

2024-08-14 11:48 UTC, narnaud commented on src/core/project.cpp
> + * Returns a list of results (QVariantMaps) with the document name and position ("file", "line", "column").
The QVariantMaps is a good idea, but I feel you need to add a small example in the documentation:

    ```js
    let findResults = Project.findInFiles("foo");
    for (let result of findResults) {
         Message.log("Filename: " + result.file);
         Message.log("Line: " + result.line);
         Message.log("Column" + result.column);
    }
    ```

2024-08-20 13:26 UTC, narnaud submitted a review, later dismissed

2024-08-21 10:23 UTC, dfaure-kdab requested changes

2024-08-21 10:23 UTC, dfaure-kdab commented on src/core/project.cpp
> +        filePath.replace('\\', '/');
The `replace` needs to happen before the check for '/' on line 441.

2024-08-21 13:30 UTC, dfaure-kdab approved these changes

2024-08-21 15:18 UTC, merged