feat: do not update docs if they are not outdated
KDAB/knut pull request #148
Opened 2024-08-13 14:44 UTC by smnppKDAB

Fixes KDAB#101

2024-08-13 14:45 UTC, smnppKDAB commented
> Fixes #101

the profiler part of the problem must wait for @dfaure-kdab for analysis

2024-08-13 18:20 UTC, narnaud commented on tools/cpp2doc/sourceparser.cpp
> +    for (const auto &fileInfo : files) {
You can't really do that, as there is no 1:1 mapping between source files and md files.

I think you need to have a file with the mapping auto-generated:
- if the file does not exist, generate it when creating the documentation (and save a timestamp in the file with the time of generation)
- if the file exists, check only the source files with a higher edit time than the timestamp in the file
- only parse those changed files, and update the mapping file

This mapping file needs to be integrated in git.
You can do something simple, like:
```
<timestamp>
Script;scriptitem.cpp
TextDocument;textdocument.cpp
...
```
Should be easy to read and write.

2024-08-13 18:21 UTC, narnaud commented on tools/cpp2doc/data.h
> +        bool isOutdated = false;
I don't think you need this property, you only need to parse the changed files.

2024-08-13 18:23 UTC, narnaud commented on tools/cpp2doc/sourceparser.cpp
> +        parseFile(sourceFile, isOutdated);
```cpp
if (isOutdated)
    parseFile(sourceFile);
```    
Then write the changes. The idea was to avoid the parsing of non-changed files completely, while you are still parsing them all.

Note: would be interesting to add a time in the main so we know what the gain is. Ideally, it should be close to 0 without any changes, while right now it's 2-3s.

2024-08-13 18:25 UTC, narnaud commented on tools/cpp2doc/sourceparser.cpp
> +    for (const auto &fileInfo : files) {
You will also need to use this file to write the Toc (DocWriter::writeToc), as you parse only new types, you won't have all of them.

2024-08-16 14:51 UTC, smnppKDAB commented
@narnaud there are still some issues with mkdocs.yml but i don't really see how to fix them. if you want to take a look at what i've done so far.

2024-08-18 12:21 UTC, narnaud reviewed
That's better, as you say you are missing the ToC but that's because you didn't fill the cached types.
Should be easy to fix.

2024-08-18 12:21 UTC, narnaud commented on tools/cpp2doc/data.h
> +    };
I don't think you need `docLastModified`.
But you probably want to save the qmlModule for regenerating the ToC (see `struct TypeBlock`).

2024-08-18 12:21 UTC, narnaud commented on tools/cpp2doc/sourceparser.cpp
> +                               });
2 things here:
- use std::ranges::find_if
- name your lambda

```cpp
auto isSameFile = [&relativeSourceFile](...)
auto it = std::ranges::find_if(m_data.matchingEntries, isSameFile);
```

2024-08-18 12:21 UTC, narnaud commented on tools/cpp2doc/sourceparser.cpp
> +        QString relativeSourceFile = baseDir.relativeFilePath(sourceFile);
You already have a `QFileInfo`, use it here: `sourceFileInfo.fileName()`
Make it const

2024-08-18 12:21 UTC, narnaud commented on tools/cpp2doc/sourceparser.cpp
> +        }
Create the shouldParse when you need it, all those lines could be done in one:
```cpp
const bool shouldParse = (it == m_data.matchingEntries.end() || sourceLastModified > it->docLastModified);
```

2024-08-18 12:21 UTC, narnaud commented on tools/cpp2doc/sourceparser.cpp
> +        QDateTime sourceLastModified = sourceFileInfo.lastModified();
Make it const

2024-08-18 12:21 UTC, narnaud commented on tools/cpp2doc/sourceparser.cpp
> +    QDateTime sourceLastModified = sourceFileInfo.lastModified();
Add some const
Create object when you need it (typically, you don't need all those except if the line start with `\\qmltype`)

2024-08-18 12:21 UTC, narnaud commented on tools/cpp2doc/sourceparser.cpp
> +                }
Worth extracting this new code into its own function, so it's easier to read:
```cpp
if (line.startsWith("\\qmltype")) {
    const auto currentType = parseType(stream, line);
    m_data.types.push_back(currentType);
    updateFileMap(file, currentType);
```
or something along those lines.

2024-08-18 12:21 UTC, narnaud commented on tools/cpp2doc/docwriter.cpp
> +    for (auto &type : m_data.types) {
I don't understand why you need this code here. It should all be done in the sourceParser, or when you load the map file.

2024-08-18 12:21 UTC, narnaud commented on tools/cpp2doc/docwriter.cpp
> +
Just before writing the Toc, you need to fill `m_data.types` based on what is in the map file. At least `name` and `qmlModule`.
This way, you can write the Toc easily. NOte that you probably also need to sort it again (maybe move line 82 here, after you fill the types)

2024-08-20 13:12 UTC, narnaud requested changes
Way better, not far from being done.

2024-08-20 13:12 UTC, narnaud commented on tools/cpp2doc/docwriter.cpp
> +    for (const auto &entry : m_data.matchingEntries) {
Like you are using `m_data.matchingEntries` for creating the ToC, you also need to use that line 53 to create the mapping `m_typeFileMap`, otherwise you may loose some inner-links.
For example, imagine that CodeDocument is changed, but not QueryMatch: right now, the documentation create a link to QueryMatch in the codedocument.md - but with the cache, it's missing the value in `m_typeFileMap` and does not create the link anymore.

2024-08-20 13:12 UTC, narnaud commented on tools/cpp2doc/data.h
> +    struct MatchingEntry
Maybe CachedType or MappedType or something like that, MatchingEntry is a bit too generic.

2024-08-20 13:24 UTC, smnppKDAB commented on tools/cpp2doc/sourceparser.cpp
> +            auto it = std::ranges::find_if(m_data.matchingEntries, isMatchingEntry);
correct, I had all duplicates in my file during my tests but the problem is fixed

2024-08-21 10:33 UTC, dfaure-kdab requested changes

2024-08-21 10:33 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +                parseFile(sourceFile);
You need to remove from mappedTypes everything concerning this source file here, to re-populate it with the current list of types. Otherwise if someone removes a type from a .cpp file, it will be there forever in the mapping file (and therefore in the TOC)

2024-08-21 10:33 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +    for (const auto &sourceFile : sourceFiles) {
This is missing the case where a source file has been deleted (or renamed). You need to iterate over mappedTypes after this loop, and clean up any source file that no longer exists.

2024-08-21 10:33 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +    const QString relativeFileName = QDir(KNUT_DOC_PATH).relativeFilePath(absoluteFileName);
Merge with previous line, no need to use relativeFilePath() at all.

2024-08-21 10:33 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +    if (it == m_data.mappedTypes.end()) {
And if it's found?

What if the qml module or the group changed, for a given type?

2024-08-21 10:33 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +        if (parts.size() == 5) {
qWarning otherwise?

2024-08-21 10:33 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +    if (!mappingFile.open(QIODevice::ReadWrite | QIODevice::Text)) {
Why ReadWrite? This method is only reading => use ReadOnly.

2024-08-21 10:33 UTC, dfaure-kdab commented on tools/cpp2doc/docwriter.cpp
> +    file.close();
Don't close explicitly: if QTextStream buffers the data, it will flush in its destructor, the file needs to remain open for that.

2024-08-21 13:23 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +            it = m_data.mappedTypes.erase(it);
You could have used std::erase_if here as well, making the code much shorter (no need for your own loop, no need to handle iterators).

2024-08-21 13:28 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +void SourceParser::updateFileMap(const QString &fileName, Data::TypeBlock currentType)
TypeBlock is a struct with many fields, it should be passed by const & rather than by value

2024-08-21 13:29 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +    const QString relativeFileName =
Make it something like relativeDocFileName, to make it clear it's about the doc and not the cpp source.

2024-08-21 14:59 UTC, dfaure-kdab submitted a review, later dismissed

2024-08-22 06:18 UTC, narnaud requested changes

2024-08-22 06:18 UTC, narnaud commented on tools/cpp2doc/docwriter.cpp
> +    std::ranges::sort(m_data.mappedTypes, byModuleAndGroupAndName);
Something missing, you apparently need to also cache the positionInGroup for types.
Those lines that you removed:
```
if (t1.positionInGroup != t2.positionInGroup)
     return t1.positionInGroup < t2.positionInGroup;
```
are important, that's what allows the document to be the first in the documentation.

Just to be sure it works, the `mkdocs.yml` file shouldn't be changed.

2024-08-22 09:24 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +        if (it->qmlModule != currentType.qmlModule || it->group != currentType.group) {
I almost wrote earlier that I wasn't a fan of this if(), because there's no harm in updating even if nothing has changed, and because it creates the risk of forgetting to add new fields to the if().
I see that I should have written that up, because it's exactly what just happened: if someone changes positionInGroup (and nothing else) then the cache won't be updated. I suggest to just remove the if().

2024-08-22 09:25 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +        return !fileInfo.exists();
Since you have to update the commit once more, here's a minor nitpick: QFileInfo::exists(path) is faster than QFileInfo(path).exists() because the latter doesn't have to construct a QFileInfo instance.

2024-08-22 09:26 UTC, dfaure-kdab commented on tools/cpp2doc/sourceparser.cpp
> +            if (positionValue >= Data::FirstInGroup && positionValue <= Data::LastInGroup) {
When would this condition be false?

2024-08-22 11:38 UTC, dfaure-kdab approved these changes

2024-08-22 14:59 UTC, narnaud approved these changes

2024-08-22 17:08 UTC, merged