feat: add a find in files panel on the GUI
KDAB/knut pull request #152
Opened 2024-08-22 14:25 UTC by smnppKDAB

Fixes KDAB#22
Depends on KDAB#21

2024-08-22 14:37 UTC, dfaure-kdab requested changes

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/findinfilespanel.cpp
> +enum FindInFilesRoles { LineRole = Qt::UserRole + 1, ColumnRole };
No enum name needed.  `enum { ... };`

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/findinfilespanel.cpp
> +    connect(m_resultsDisplay, &QTreeWidget::itemDoubleClicked, this, [this](QTreeWidgetItem *item, int) {
not needed, itemActivated() is emitted on double-click too

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/findinfilespanel.cpp
> +        qWarning() << "The text to search for is empty";
That's not really worth a warning. It's not a coding error. It's a normal condition.

Alternatively, you could disable the button when the text is empty. That would probably be better.

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/findinfilespanel.cpp
> +        findInFiles(m_searchInput->text());
You could simplify this by removing the argument, and calling `m_searchInput()->text()` inside the method.

Then these two connects don't need a lambda anymore, you can just connect to `&FindInFilesPanel::findInFiles` as the 4th argument.

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/findinfilespanel.h
> +    void displayResults(const QVariantList &results) const;
Why public?

(related to the dead code further down, can be made private after removing the dead code)

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/findinfilespanel.h
> +#include <QLineEdit>
Use forward declarations instead, for anything that's only used as a pointer in this file, like QLineEdit, QToolButton, QTreeWidget

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/mainwindow.cpp
> +void MainWindow::displayFindResults(const QVariantList &results) const
Who calls this method?

I think it's dead code.

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/findinfilespanel.cpp
> +        lineItem->setData(1, ColumnRole, column);
Set the data in column 0, not 1 (which doesn't exist)

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/findinfilespanel.cpp
> +    const int column = item->data(1, ColumnRole).toInt();
column 0 here too, obviously

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/findinfilespanel.cpp
> +#include "guisettings.h"
unused?

2024-08-22 14:37 UTC, dfaure-kdab commented on src/gui/mainwindow.h
> +    FindInFilesPanel *const m_findInFilesPanel = nullptr;
Doesn't really need to be a member variable. See logPanel for an example.

2024-08-26 10:23 UTC, dfaure-kdab requested changes

2024-08-26 10:23 UTC, dfaure-kdab commented on src/gui/mainwindow.h
> +    void displayFindResults(const QVariantList &results) const;
You forgot to remove this.

2024-08-26 10:23 UTC, dfaure-kdab commented on src/gui/mainwindow.h
> +class FindInFilesPanel;
You forgot to remove this.

2024-08-26 10:23 UTC, dfaure-kdab commented on src/gui/findinfilespanel.h
> +    QToolButton *m_searchButton;
Doesn't need to be a member variable.

2024-08-26 13:49 UTC, dfaure-kdab approved these changes

2024-08-26 14:19 UTC, narnaud approved these changes

2024-08-26 15:42 UTC, merged