improve search in document
KDAB/knut pull request #160
Opened 2024-09-02 05:05 UTC by mgiroday

- **fix: handle escaped characters when reading XML files**
- **feat: parse ribbon description files for RC files**
- **ci: Remove the reference to base_ref in docs job**
- **.codespellrc - add codespell configuration**
- **fix: deleteLine method name in logging**
- **chore: cleanup gitreview config file**
- **docs: clarify the difference between Project::get and Project::open**
- **fix: cleanup the Ribbon API and documentation**
- **ci: Install plantuml plugin before building docs**
- **feat: Create a JsonDocument**
- **fix: Fix message map extraction when namespaces are used**
- **fix: put everything from utils/strings.h into the namespace Utils**
- **chore: Reduce workspace extensions for VSCode**
- **feat: add option to return the settings from the CLI**
- **docs: Cleanup documentation**
- **feat: add API to create a ui file in QtUiDocument**
- **feat: Add utility class to help write Qt Ui files**
- **refactor: move back the frame conversion to code**
- **refactor: remove the rc2ui.js file, conversion is now static**
- **refactor: increment duplicate ids in RcFile**
- **fix: rename `strings.h` into `string_helper.h`**
- **feat!: refactor the ScriptDialog API for progressbar**
- **chore: rename ConversionProgressDialog into ScriptProgressDialog**
- **feat!: Remove the uiFilePath property from ScriptDialog**
- **test: add tests for the examples**
- **feat: add support for QmlJs via tree-sitter-qmljs**
- **refactor(cmake): Move version into version.txt**
- **fix(tests): update mfc-utils for tests to pass**
- **chore: Cleanup unused includes**
- **chore: Fix std::move usage with const variables**
- **chore: Remove unescessary ;**
- **chore: Remove some copy, use const & when needed**
- **chore: Multiple small cleanups**
- **chore: Const-ify some methods/variables**
- **fix: use /O3 with MSVC rather than -O3**
- **fix: adapt optimization compilation to microsoft compiler**
- **chore: Cleanup CMake targets**
- **fix: use correct variable for toolButton**
- **docs(example): example script to get/set data**
- **feat: introduce Qml to parser**
- **fix: we build against qt6 only now (#78)**
- **fix: Remove version from import**
- **chore: Add missing license to examples**
- **feat: Add ribbon to the RcViewer**
- **feat: add a ribbon model for rcviewer"**
- **fix: default ui windowTitle is "Form" => it can be translated => remove it (#81)**
- **ci: Add release-please workflow**
- **fix(build): Fix debug build on Windows**
- **fix: modification of the setTranslation function for the case where the node is untranslated**
- **fix: const'ify value in knutstyle**
- **fix: const'ify pointer**
- **fix: in qt6 QVector is an alias to QList**
- **refactor: reduce LSP dependencies in Core**
- **docs: review the Utils API**
- **docs: remove old LSP API**
- **fix(docs): Fix an issue with `array<>` in doc**
- **docs: Review the item's API**
- **docs: Review the `Document` and `Project` API**
- **refactor: Add logging for UserDialog return values**
- **chore(ci): Use GitHub upload-pages-artifact and deploy-pages actions**
- **feat: allow to search string in qttsview**
- **refactor!: Rename Script QML module to Knut**
- **chore(ci): Remove pre_commit job from GH Actions**
- **fix: Use Qt_QPA_PLATFORM=offscreen for testing**
- **fix: add stdset="0" we don't want to generate property**
- **chore(cmake): Re-enable docs target by default**
- **refactor!: Change the test API for scripts**
- **chore: update mfc-utils and photonwidgets sub-modules**
- **fix: allow to replace by empty string (=> remove text)**
- **fix: save settings file in different directory in testing mode**
- **fix: Fix saving stringlist in Settings via script**
- **feat: Select Smaller/Larger/Next/Previous Syntax Nodes (#105)**
- **chore: Bump version of photonwidgets**
- **docs: Review QtTsDocument API**
- **fix: Add missing properties to ScriptRunner::isProperty**
- **docs: Review RcDocument API**
- **refactor!: Remove TextLocation class**
- **refactor!: Remove TextRange class**
- **feat: Add a code view with button for TreeSitter**
- **refactor: Improve document toolbar**
- **chore: Add missing licenses for the icons used inside the application**
- **fix: Fix crash in TreeSitter inspector with non-code document**
- **fix: Delete the TreeSitter inspector when closed**
- **feat: Skip macros in C++ during parsing (#116)**
- **feat: added line property for a message node (#122)**
- **feat: add a method to change the context of a message (#121)**
- **chore(docs): Fix & Improve contribution docs**
- **chore: update mfc-utils sub-module (#124)**
- **feat: Add symbol listing for Qml (#79)**
- **fix: save settings on exit (#125)**
- **chore: update mfc-utils sub-module**
- **feat: improve nextStep API in ScriptDialog (#129)**
- **feat: Add TypedSymbol**
- **fix: Capturing of return types in FunctionSymbol**
- **build: Fix include issue with TreeSitter and unicode**
- **fix: do not run tests if the path to the directory doesn't exist**
- **fix: improve script performance by changing QTreeView settings**
- **fix: Make Symbols & query... calls consistent**
- **fix: simplify the API documentation (#132)**
- **feat: Scheme syntax highlighting for TreeSitter**
- **fix!: Remove treesitter transformations**
- **feat: add a way to initialize script dialog from command line (#136)**
- **fix: change syntax of comments to remove warning (#139)**
- **chore: update mfc-utils sub-module (#140)**
- **feat: Handle QTextEdit in the ScriptDialogItem (#141)**
- **fix: flush spdlog messages also when logging to stderr (#142)**
- **fix: exit knut if there is an error in qml test (#147)**
- **fix: remove unused forward declaration**
- **docs: Note Windows build issues, provide steps to resolve (#144)**
- **fix: allows describing type documentation with nested brackets and commas**
- **feat: Add reuse and fix lint issues**
- **feat: Saving & loading TS queries in inspector**
- **feat: Custom treesitter grammar**
- **feat: add a find in files API to Project (#143)**
- **feat: do not update docs if they are not outdated (#148)**
- **feat: Add some more API to JsonDocument (#76)**
- **fix: minor REUSE issues (#153)**
- **feat: add a find in files panel on the GUI (#152)**
- **feat: add a removeLines method in CppDocument (#154)**
- **fix: move LogHighlighter from Gui to Core (#155)**
- **feat: add a way to display log in a ScriptDialog (#157)**
- **fix: move return in the changeValue method to ensure proper execution flow (#156)**
- **fix: use asKeyValueRange() instead of keys() (#159)**
- **feat: improve search in document (#25)**

2024-09-02 18:20 UTC, narnaud requested changes
THere's an architecture issue here:
- the API you introduced in Core only emit signals, so that's not something a user can use from a script
Yes. This was the wrong way to do it indeed. I have introduced a 'setFindWidget(...)'  which function which is called from the MainWindow.
Fixed. Thank you. 
-
- HighlightSearchDelegate shouldn't be in Core, but gui only <-- Fixed. Thank you.

IMO there shouldn't be any specific changes into Core, only gui. So we need a way for the FindWidget to work on views instead of working on document. Meaning you need some sort of interfaces for the searchable views to call from the FinWidget. Fixed.
Concerning the rc views it is a bit different as we have 3 different views to handle for the search. 
So each view has its own search widgets. 

I like the idea of the highlight delegate, but don't make the color blue (it's hardly readable for me), maybe use bold and/or underline. <--- Fixed (using bold - looks better indeed). Thank you.

I'm not sure we want to do replace on ts and ui view yet, so maybe have a way to hide this part for now when on the ts or ui view. Fixed (I saved the find and replace code locally in case we want to add this feature at some point) .

Last thing, when I press escape and hide the find widget, I would expect to reset the search delegate.
Yep - did not notice that - fixed. Thank you.

2024-09-10 09:11 UTC, mgiroday commented
Comments fixed. Ready for review.

2024-09-11 17:41 UTC, narnaud requested changes
For now, don't do anything on the rcfileview.
In term of usability, I would like to use the same find widget as the rest, I need to figure out how to do that though. So let's remove that out.

2024-09-11 17:41 UTC, narnaud commented on src/gui/qttsview.cpp
> +    , m_currentSearchText(QString())
No need for this line, it's done automatically

2024-09-11 17:41 UTC, narnaud commented on src/gui/qttsview.cpp
> +    connect(findWidget, &FindWidget::findWidgetHiding, this, [this]() {
Please name your lambda, this will avoid the need of the comment:
```
auto updateDisplay = []()...
connect(....., updateDisplay);
```

2024-09-11 17:41 UTC, narnaud commented on src/gui/qttsview.h
> +    Q_ENUM(FindFlag)
No need for a new flag, use the flags coming from the FindWidget directly `Core::TextDocument::*`

2024-09-11 17:41 UTC, narnaud commented on src/gui/qtuiview.cpp
> +    connect(findWidget, &FindWidget::findWidgetHiding, this, [this]() {
same here, name your lambda

2024-09-11 17:41 UTC, narnaud commented on src/gui/qtuiview.h
> +    Q_ENUM(FindFlag)
No need for this flag

2024-09-20 07:22 UTC, Montel commented on src/gui/qtuiview.cpp
> +    , m_currentSearchText(QString())
This line is not necessary

2024-10-23 10:29 UTC, mgiroday commented on src/gui/qtuiview.cpp
> +    , m_currentSearchText(QString())
Yep fixed. Thank you.

2024-10-23 10:30 UTC, mgiroday commented on src/gui/findwidget.h
> +    void findWidgetHiding();
Yep, fixed. Thank you.

2024-10-23 10:32 UTC, mgiroday commented on src/gui/findwidget.ui
> +    <widget class="QFrame" name="findFrame">
I have reset to the original UI and show/hide the widgets individualy as suggested.
Fixed. Thank you.

2024-10-23 10:34 UTC, mgiroday commented on src/gui/highlightsearchdelegate.cpp
> +{
Whope, did not notice (the offset was 3 px...) . I found  a solution that retrieve the QStyle margin for the left side of the cell. Much better than hardcoding an offset.
Fixed. Thank you.

2024-10-23 10:35 UTC, mgiroday commented on src/gui/qttsview.cpp
> +    , m_currentSearchText(QString())
Right. Fixed. Thank you.

2024-10-23 10:36 UTC, mgiroday commented on src/gui/qttsview.cpp
> +    connect(findWidget, &FindWidget::findWidgetHiding, this, [this]() {
Oooops, sorry!
Fixed. Thank you.

2024-10-23 10:37 UTC, mgiroday commented on src/gui/qttsview.h
> +    Q_ENUM(FindFlag)
Yep, I was focused about a FindForward but that was not needed indeed. It is now defaulted.
Fixed. Thank you.

2024-10-23 10:41 UTC, mgiroday commented on src/gui/qtuiview.cpp
> +    connect(findWidget, &FindWidget::findWidgetHiding, this, [this]() {
Yep. Fixed. Thank you.

2024-10-23 10:49 UTC, mgiroday commented on src/gui/qtuiview.h
> +    Q_ENUM(FindFlag)
Yep. Fixed

2024-10-23 11:40 UTC, mgiroday commented
Comments fixed. Ready for review. 
ote: I have reverted all changes related to rcfileview as you have mentioned above.

2024-10-31 14:31 UTC, narnaud commented
I did some changes, but apparently I can't edit this PR.
So the new PR is #215 
Thank you Michel, nice starting point for me.

2024-10-31 14:31 UTC, closed without merging