fix: Fix combobox's width for API executor
KDAB/knut pull request #219
Opened 2024-11-17 16:36 UTC by narnaud

When changing files with the API executor displayed, the combobox didn't
adapt to its content.

Fix #164

2024-11-18 10:49 UTC, LeonMatthesKDAB requested changes
This is definitely improving the UX, but this should be set in the .ui file, not the .cpp file, right?

2024-11-18 10:49 UTC, LeonMatthesKDAB commented on src/gui/apiexecutorwidget.cpp
> +    ui->apiComboBox->setSizeAdjustPolicy(QComboBox::AdjustToContents);
Shouldn't this rather be changed in the apiexecutorwidget.ui file directly, instead of after construction?

2024-11-18 10:54 UTC, LeonMatthesKDAB commented on src/gui/apiexecutorwidget.cpp
> +    ui->apiComboBox->setSizeAdjustPolicy(QComboBox::AdjustToContents);
Hm, even weirder: for me it's not adjusting the size correctly, even with this patch included???
![image](https://github.com/user-attachments/assets/6b7a7f36-d1f8-43a0-ac6d-1308fd810b2b)

2024-11-18 16:46 UTC, narnaud commented on src/gui/apiexecutorwidget.cpp
> +    ui->apiComboBox->setSizeAdjustPolicy(QComboBox::AdjustToContents);
Could be in ui or code, no big deal for me. But I moved it to the ui file.
As for your screenshot, unfortunately I think it's a bug in the style. If you tried to:
- open a txt file
- open the API executor line
- open a cpp file
You'll see the combobox change size, it's just not enough to display everything: IMO a style bug.

2024-11-28 15:03 UTC, LeonMatthesKDAB approved these changes

2024-11-29 12:43 UTC, merged