feat: Add search for rc files
KDAB/knut pull request #220
Opened 2024-11-18 19:19 UTC by narnaud

For now, only search inside the list of data IDs.
We may extend this later on if useful/needed.

To do that, I had to move the rcui code inside the gui library, so I can use the FindInterface.

Fix #25

2024-11-28 14:04 UTC, LeonMatthesKDAB requested changes
Overall the change is okay, but the `SearchableViewInterface` name is confusing, as this class implements "Find", not "Search" and actually isn't an "interface".

2024-11-28 14:04 UTC, LeonMatthesKDAB commented on src/gui/searchableviewinterface.cpp
> +SearchableViewInterface::SearchableViewInterface(QAbstractItemView *view)
This name is confusing, as it's not actually an "Interface".
An interface I would expect to inherit from and override methods on (like you do with `FindInterface`).
This doesn't do that, it's rather an adapter/proxy, that allows to conveniently forward the implementation of the `FindInterface` to a `QAbstractItemView`.

Also: "Search" is a new term here, why not just "find"?
As that's used everywhere else.

So maybe `FindAdapter` or `FindProxy`?
The latter would somewhat fit  with the QSortFilter**Proxy**Model

2024-11-28 14:04 UTC, LeonMatthesKDAB commented on src/gui/rcui/rcfileview.cpp
> +#include "../searchableviewinterface.h"
prefer `"gui/searchableviewinterface.h"`

2024-11-29 13:24 UTC, narnaud commented on src/gui/searchableviewinterface.cpp
> +SearchableViewInterface::SearchableViewInterface(QAbstractItemView *view)
I agree, it was an interface at first, and I changed mid-way. `FindAdapter` is way better.

2024-12-13 15:11 UTC, LeonMatthesKDAB approved these changes

2024-12-13 15:11 UTC, merged