Review some API and update documentation
KDAB/knut pull request #80
Opened 2024-07-01 18:28 UTC by narnaud

- docs: Review the `Document` and `Project` API
- docs: Review the item's API
- fix(docs): Fix an issue with `array<>` in doc
- docs: remove old LSP API
- docs: review the Utils API

Related to #54

2024-07-03 14:38 UTC, LeonMatthesKDAB requested changes
I'd prefer to not completely get rid of the logging, for the LSP functions, plus another minor nitpick, but otherwise looks good :)

2024-07-03 14:38 UTC, LeonMatthesKDAB commented on src/core/userdialog.cpp
> +    LOG("UserDialog::getOpenFileName", caption, dir, filters);
Should this use LOG_RETURN as well?
Same for the other UserDialog functions :thinking:

2024-07-03 14:38 UTC, LeonMatthesKDAB commented on src/core/codedocument.cpp
> -    LOG("CodeDocument::hover");
I would prefer to replace this with `spdlog::debug()`.

If there are any issues with this code, we can easier spot the root cause instead of having to debug random LSP failures that occur apparently out of nowhere :)

Same with the other LSP methods.

2024-07-03 17:58 UTC, narnaud commented on src/core/userdialog.cpp
> +    LOG("UserDialog::getOpenFileName", caption, dir, filters);
Not really, the LOG_RETURN is mostly used for API that is used inside the GUI, to be able to create a script from the history log.
For example, when doing a find on the current selected text, teh LOG_RETURN is used to match the return value of `TextDocument::selectedText` and the parameter of `TextDocument::find`.

Here, those methods are only used in scripts, and never called from teh GUI, so we don't need that. We still need the log to see what's going on when running the script.

2024-07-03 17:58 UTC, narnaud commented on src/core/codedocument.cpp
> -    LOG("CodeDocument::hover");
Good idea, fixed.

2024-07-05 11:16 UTC, LeonMatthesKDAB commented on src/core/userdialog.cpp
> +    LOG("UserDialog::getOpenFileName", caption, dir, filters);
Hm, okay. But then shouldn't we just use `spdlog::trace` or `spdlog::debug`?

2024-07-05 12:06 UTC, narnaud commented on src/core/userdialog.cpp
> +    LOG("UserDialog::getOpenFileName", caption, dir, filters);
Ok, you want to know the return value returned. LOG_RETURN won't help here, as it's logging the "tag" of the return value, not the return value itself.

I've added spdlog::debug, this way we will see it even if we remove the trace (that's where the `LOG` are logged).

Just review the last commit, rest has not changed.

2024-07-05 12:35 UTC, LeonMatthesKDAB approved these changes

2024-07-08 11:22 UTC, merged