refactor: reduce LSP dependencies in Core
KDAB/knut pull request #84
Opened 2024-07-02 18:39 UTC by narnaud

- remove lsp_utils in knut-lsp
- create a lsp_utils with lsp methods in Core::Utils namespace
- cleanup methods from TextLocation and CodeDocument

Fix #67

2024-07-03 14:46 UTC, LeonMatthesKDAB requested changes
Please use references instead of pointers where appropriate. I also don't understand why this still builds without textlocation.cpp in CMake, but otherwise looks good.

2024-07-03 14:46 UTC, LeonMatthesKDAB commented on src/core/lsp_utils.h
> +std::string documentToUri(const TextDocument *textDocument);
The implementation expects the textDocument to not be a nullptr. So prefer to use a reference instead of a pointer.

2024-07-03 14:46 UTC, LeonMatthesKDAB commented on src/core/CMakeLists.txt
> -    textlocation.cpp
Why were they removed from CMake? The files still exist :thinking:

2024-07-03 17:51 UTC, narnaud commented on src/core/CMakeLists.txt
> -    textlocation.cpp
Oups, I was in the middle of something else...

2024-07-03 17:52 UTC, narnaud commented on src/core/lsp_utils.h
> +std::string documentToUri(const TextDocument *textDocument);
In fact, this method can stay in CodeDocument, it doesn't add any LSP dependencies, and it makes sense to keep it there.

2024-07-05 11:15 UTC, LeonMatthesKDAB commented on src/core/lsp_utils.h
> +std::string documentToUri(const TextDocument *textDocument);
Ah, okay, the same question about pointer vs. reference also applies to lspFromPos, lspToPos and lspToRange.
Sorry, I forgot to mention that in the initial review.
These should all take TextDocument references I think instead of pointers.

2024-07-05 11:55 UTC, narnaud commented on src/core/lsp_utils.h
> +std::string documentToUri(const TextDocument *textDocument);
Done

2024-07-05 12:00 UTC, LeonMatthesKDAB approved these changes

2024-07-05 12:22 UTC, merged